### ISSUE TITLE
Error 505 (Requested URL returned error)

### ISSUE THREAD

**Issue by ottosmops** [appstract/laravel-opcache#101]
Since today I get this error:

```
php artisan opcache:compile --force
Compiling scripts...
The requested URL returned error: 500 Internal Server Error
Url: https://myurl/opcache-api/compile?key=akey...&force=1
```

How can I solve this?

**Comment by repat** [comment]
Look at what the 500 error is, possibly because the URL can't be found. It should be 127.0.0.1, you can try hardcoding it in `/etc/hosts`

**Comment by ottosmops** [comment]
Thank you! Sorry, it simply was a syntax error in an unused file. I dont know why this led to this error right now, because the syntax bug was there for a while.
