### ISSUE TITLE
Cannot redeclare Composer\Autoload\includeFile() (previously declared in /code/vendor/composer/ClassLoader.php:442)

### ISSUE THREAD

**Issue by mpyw** [appstract/laravel-opcache#106]
Possibly related to #75.

`opcache.dups_fix` seems to be able to solve this problem, but it doesn't work as expected...

![image](https://user-images.githubusercontent.com/1351893/79864713-e25a4300-8414-11ea-8a7f-1f6e83ec7dd2.png)
![image](https://user-images.githubusercontent.com/1351893/79864742-eede9b80-8414-11ea-891e-e820d184e307.png)

We don't see any errors in the terminal, but we confirmed Sentry error report has been actually sent.

**Comment by ovanschie** [comment]
Maybe exclude the autoloader in config?

**Comment by mpyw** [comment]
My current attempt:

![image](https://user-images.githubusercontent.com/1351893/80535168-57141b00-89db-11ea-857a-4a881b59f777.png)

But it believe it be excluded by default.

**Comment by mpyw** [comment]
Resolved by:

```diff
- base_path('vendor/composer/composer/src/Composer/Autoload/ClassLoader.php')
+ 'Autoload'
```

However, we'd better add `notPath` directive in addition to `exclude`.

**Comment by genesiscz** [comment]
@ovanschie could you fix this in place so we dont have to visit this issue on every other project, please? I'd make a PR, but not sure this is sufficient and safe enough to just jump into it

**Comment by ovanschie** [comment]
I still never had this issue before,  so if anyone can confirm one of the above things works, i'll add it.

**Comment by genesiscz** [comment]
I confirm the base path works

**Comment by ovanschie** [comment]
> I confirm the base path works on every single project of mine, all of them running Laravel 7

and just 'Autoload' ??

**Comment by genesiscz** [comment]
yes, seems to be working
