### ISSUE TITLE
TypeError:  Illuminate\Http\Client\PendingRequest::withHeaders()

### ISSUE THREAD

**Issue by boopathydreams** [appstract/laravel-opcache#107]
Hi,

After following all the steps I get the following error. I couldn't find details regarding this anywhere.
I get the error on all artisan opcache commands. 

```
Argument 1 passed to `Illuminate\Http\Client\PendingRequest::withHeaders()` must be of the type array, null given, called in `\vendor\laravel\framework\src\Illuminate\Http\Client\Factory`.
php on line 283

at C:\wamp64\www\cms\vendor\laravel\framework\src\Illuminate\Http\Client\PendingRequest.php:231
    227|      *
    228|      * @param  array  $headers
    229|      * @return $this
    230|      */
  > 231|     public function withHeaders(array $headers)
    232|     {
    233|         return tap($this, function ($request) use ($headers) {
    234|             return $this->options = array_merge_recursive($this->options, [
    235|                 'headers' => $headers,


  1   C:\wamp64\www\cms\vendor\laravel\framework\src\Illuminate\Http\Client\Factory.php:283
      Illuminate\Http\Client\PendingRequest::withHeaders()

  2   C:\wamp64\www\cms\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php:261
      Illuminate\Http\Client\Factory::__call("withHeaders")

```
TIA

**Comment by ovanschie** [comment]
Do you have this in your config?

https://github.com/appstract/laravel-opcache/blob/master/config/opcache.php#L7

**Comment by genesiscz** [comment]
yes

**Comment by genesiscz** [comment]
I fixed this with  php artisan config:clear
because my config was cached

**Comment by boopathydreams** [comment]
> Do you have this in your config?
> 
> https://github.com/appstract/laravel-opcache/blob/master/config/opcache.php#L7

Yes, I do have that.
I apologize for the delayed response as I continued working after disabling opcache temporarily.

Also, config:clear is the first thing anyone would do. I did that too. 

Let me try today and post the update.

Thanks.

**Comment by ovanschie** [comment]
@boopathydreams fixed?
