### ISSUE TITLE
Composer require fails on older php version

### ISSUE THREAD

**Issue by DJPretorius** [appstract/laravel-opcache#108]
I tried to require this package, version 3.2.1, via composer. This was the command entered:
`composer require appstract/laravel-opcache:^3.2.1 -vvv`
The requirements on [packagist](https://packagist.org/packages/appstract/laravel-opcache#3.2.1) says that version 3.2.1 needs php ^7.1.3.

But i get this error: 
```
Problem 1
    - This package requires php 7.3 but your PHP version (7.2.24) does not satisfy that requirement.
```
Using Laravel v6.18.3.

Am I missing something? Please can you assist?

**Comment by ovanschie** [comment]
strange, the package and all the dependencies require php 7.1 or 7.2.

you can try with --ignore-platform-reqs

**Comment by DJPretorius** [comment]
Yes that worked. Thank you so much
