### ISSUE TITLE
LTS Laravel 6 is using version 3.2 which requires abandoned package (appstract/lush-http)

### ISSUE THREAD

**Issue by FilipQL** [appstract/laravel-opcache#110]
The documentation ([README.md](https://github.com/appstract/laravel-opcache/blob/master/README.md)) states that:

> This package requires Laravel 7 or newer.

I was able to install it on Laravel 6 (**LTS**), but the installed version is 3.2 which uses **abandoned** package [appstract/lush-http](https://github.com/appstract/lush-http). 
Does that mean there will be no fixes/updates/improvements of this package for Laravel 6? 

I am asking this because Laravel 6 is **LTS** and has longer support than Laravel 7: https://laravel.com/docs/master/releases 
It makes sense to support the latest LTS version of Laravel with the package version that is actively being updated/fixed/improved, right? :)

**Comment by ovanschie** [comment]
No active support for Laravel 6. We migrated to the built in http client in Laravel 7.
