### ISSUE TITLE
The requested URL returned error: 500 Internal Server Error

### ISSUE THREAD

**Issue by brucek2** [appstract/laravel-opcache#12]
I am developing on homestead and have made these configurations:
/etc/hosts:
127.0.0.1  lcatch5.app

.env
APP_URL=lcatch5.app

When I run php artisan opcache:status, I get:
  [Appstract\LushHttp\Exception\LushRequestException]          
  The requested URL returned error: 500 Internal Server Error

The error line from the Laravel log is:
[2017-03-02 20:44:45] local.ERROR: Appstract\LushHttp\Exception\LushRequestException: The requested URL returned error: 500 Internal Server Error in /home/vagrant/Code/lcatch5/vendor/appstract/lush-http/src/Request/CurlRequest.php:121

In the web server error log I see (ignore timestamp mismatch):
2017/03/02 18:52:58 [error] 1999#1999: *35 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class 'App\Http\Controllers\Controller' not found in /home/vagrant/Code/lcatch5/vendor/appstract/laravel-opcache/src/Http/Controllers/OpcacheController.php on line 11

What am I missing?

Is it possible you require/assume that the namespace for Controller.php is the current 5.x default of App\Http\Controllers? My project began way back in laravel 4.x and still uses the legacy namespaces from that time (i.e., Controller is at root.)

**Comment by brucek2** [comment]
OK confirmed: issue was with the the assumed namespace of Controller. I converted all my files to the 5.x convention and it ran fine.

I'd close this issue now but maybe you want to add a line to the install instructions about the namespace requirement first in case it helps the next user?

**Comment by ovanschie** [comment]
Thanks for letting us know! 

I think we can fix this by including our own basecontroller in stead of including the one from App\Http.
