### ISSUE TITLE
Question: How to use it with Laravel Octane?

### ISSUE THREAD

**Issue by litan1106** [appstract/laravel-opcache#128]
Should we run it after we start the octane command?

php artisan octane:star

php artisan opcache:clear

php artisan opcache:compile {--force}

**Comment by nasyrov** [comment]
@litan1106 hi there, there's no point in using this package with Octane. Please check the way Octane works.

**Comment by litan1106** [comment]
I think we still need cache the custom application codes. It seemed faster with opcached.

**Comment by nasyrov** [comment]
@litan1106 with Octane your code loads once, you need opache when you use something like php-fpm
