### ISSUE TITLE
what is the reason adding Guzzle as dependency?

### ISSUE THREAD

**Issue by erlangparasu** [appstract/laravel-opcache#135]
https://github.com/appstract/laravel-opcache/blob/d2ce88cddda6af54c14d1f9ceaaf94b54f38f9d3/composer.json#L23

**Comment by zlodes** [comment]
Hi!

It uses Laravel HTTP Client. It requires Guzzle.

https://github.com/appstract/laravel-opcache/blob/d2ce88cddda6af54c14d1f9ceaaf94b54f38f9d3/src/CreatesRequest.php#L17
