### ISSUE TITLE
OPCache not working in All domains

### ISSUE THREAD

**Issue by jalpab** [appstract/laravel-opcache#140]
I have Zend opcache compiled with PHP7.4 and enabled with following configuration
opcache.memory_consumption=128
opcache.interned_strings_buffer=8
opcache.max_accelerated_files=4000
opcache.revalidate_freq=0
opcache.validate_timestamps = 0
opcache.fast_shutdown=0
opcache.enable_cli=0
opcache.enable=1
When i checked it with one of my domains in my server using phpinfo(); , There i can see Opcache is enabled and running. But when i checked the same with other domains, Opcache is showing as Disabled. How can i make opcache running in all domains. I never had this issue in the past. I wonder how this happened now?

Need suggestions please.

**Comment by ovanschie** [comment]
Not an issue with the package
