### ISSUE TITLE
Why use http routes?

### ISSUE THREAD

**Issue by jaketoolson** [appstract/laravel-opcache#19]
Why do your artisan commands call http routes?  It seems like an undesirable exposure to routes you wouldn't otherwise want available via http, even though you have middleware rules.  Create a service or bus ?

**Comment by mstaack** [comment]
flushing opcache only works from a webserver like nginx/apache..
in php cli flushing opcache is not possible...

**Comment by jaketoolson** [comment]
Makes sense!

**Comment by kohenkatz** [comment]
There is actually a setting `opcache.enable_cli` that determines this.  It was disabled by default before, but is now enabled by default as of PHP 7.1.2.

**Comment by ovanschie** [comment]
@kohenkatz that is not what it is for. CLI and FPM use separate instances of PHP both with it's own config and cache. http://php.net/manual/en/opcache.configuration.php#ini.opcache.enable-cli
