### ISSUE TITLE
Laravel 5.4 and php 7.1 not install

### ISSUE THREAD

**Issue by trixanapp** [appstract/laravel-opcache#2]
Problem 1
    - Installation request for appstract/laravel-opcache ^0.0.1 -> satisfiable by appstract/laravel-opcache[0.0.1].
    - appstract/laravel-opcache 0.0.1 requires guzzlehttp/guzzle ^5.3 -> satisfiable by guzzlehttp/guzzle[5.3.0, 5.3.1, 5.3.x-dev] but these conflict with your requirements or minimum-stability.

**Comment by ovanschie** [comment]
This is probably caused by a conflict with another package. I will try to create a version that does not require Guzzle, to solve these conflicts.

**Comment by trixanapp** [comment]
Thank you **@ovanschie** .

**Comment by Cannonb4ll** [comment]
+1

**Comment by pe3udent** [comment]
+1

**Comment by ctf0** [comment]
@ovanschie i have `"guzzlehttp/guzzle": "^6.2",` installed, maybe this could be the issue as the package require an older one.

however i believe the version should be pumped as u r requiring `php >= 5.6` and in this case we should use v6 of guzzle https://packagist.org/packages/guzzlehttp/guzzle#6.2.2
