### ISSUE TITLE
 There are no commands defined in the "opcache" namespace.

### ISSUE THREAD

**Issue by tommoholmes** [appstract/laravel-opcache#20]
I have been install with running 
```composer require appstract/laravel-opcache``` 
and setup 
```
// config/app.php
'providers' => [
    ...
    Appstract\Opcache\OpcacheServiceProvider::class,
];
``` 
and then `composer dump-autoload` but I still get error like this
```  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "opcache" namespace.       
  Did you mean this?                                              
      cache
```
please help me

I'm use laravel 5.4

**Comment by gizburdt** [comment]
I tried it with a clean install and it works, so maybe some caching. Can you run `composer dump-autoload -o`, `php artisan optimize`, `php artisan clear-compiled` and `php artisan cache:clear`?

**Comment by tommoholmes** [comment]
I have been running this command, but still error

**Comment by tommoholmes** [comment]
I have solved it like this:

php artisan cache:clear
php artisan config:cache
but I get error like this
```                                                       
  [Appstract\LushHttp\Exception\LushRequestException]  
  The requested URL returned error: 404 Not Found
```

**Comment by Alexmg86** [comment]
+1 The requested URL returned error: 404 Not Found | Laravel 5.2

**Comment by ovanschie** [comment]
`artisan route:clear` ?

**Comment by Alexmg86** [comment]
<img width="517" alt="2017-04-08 17 40 51" src="https://cloud.githubusercontent.com/assets/7482040/24829853/9112be7a-1c82-11e7-96be-ee1eb41c6b37.png">

**Comment by ovanschie** [comment]
@Alexmg86 have you set the correct APP_URL?

**Comment by Alexmg86** [comment]
Sorry :( this my setting
app.php
'url' => env('APP_URL', 'http://renot'),
.env
APP_URL=renot
DB_HOST=renot
DB_DATABASE=renot

maybe need more? :)

**Comment by ovanschie** [comment]
@Alexmg86 it will make a request to http://renot/opcache-api/config does this work in your browser?

**Comment by Alexmg86** [comment]
writing one line: {"result":false}

**Comment by Alexmg86** [comment]
ohhh ))) i'm stupid ))
i forget turn on this option in Mamp pro. And now working perfect. Many thanks!!!!

**Comment by ovanschie** [comment]
@Alexmg86 cool 👍
