### ISSUE TITLE
Laradock - Failed to connect to localhost port 80: Connection refused

### ISSUE THREAD

**Issue by brentpep** [appstract/laravel-opcache#21]
I'm using laradock and trying to run `php artisan opcache:clear` in the workspace container where my projects are located. Any ideas?

**Comment by ovanschie** [comment]
You run it from inside laradock ?

**Comment by brentpep** [comment]
Yeah, running it from inside the laradock workspace container.

It also seems to be having issues running on [Forge](https://forge.laravel.com). This is the error:

```
[Appstract\LushHttp\Exception\LushRequestException]  
The requested URL returned error: 404 Not Found  
```

**Comment by ovanschie** [comment]
If you have opcache enabled already, then you need to restart nginx. Else try to run `composer dump-autoload -o`, `php artisan clear-compiled`, `php artisan cache:clear` and` php artisan optimize`

**Comment by brentpep** [comment]
Unfortunately, the results are still the same.

Opcache is enabled and I restarted nginx, as well as ran those commands you mentioned. 

```
php -i | grep "opcache"

/etc/php/7.0/cli/conf.d/10-opcache.ini,
opcache.blacklist_filename => no value => no value
opcache.consistency_checks => 0 => 0
opcache.dups_fix => Off => Off
opcache.enable => On => On
opcache.enable_cli => Off => Off
opcache.enable_file_override => Off => Off
opcache.error_log => no value => no value
opcache.fast_shutdown => 0 => 0
opcache.file_cache => no value => no value
opcache.file_cache_consistency_checks => 1 => 1
opcache.file_cache_only => 0 => 0
opcache.file_update_protection => 2 => 2
opcache.force_restart_timeout => 180 => 180
opcache.huge_code_pages => Off => Off
opcache.inherited_hack => On => On
opcache.interned_strings_buffer => 4 => 4
opcache.lockfile_path => /tmp => /tmp
opcache.log_verbosity_level => 1 => 1
opcache.max_accelerated_files => 2000 => 2000
opcache.max_file_size => 0 => 0
opcache.max_wasted_percentage => 5 => 5
opcache.memory_consumption => 64 => 64
opcache.optimization_level => 0x7FFFBFFF => 0x7FFFBFFF
opcache.preferred_memory_model => no value => no value
opcache.protect_memory => 0 => 0
opcache.restrict_api => no value => no value
opcache.revalidate_freq => 2 => 2
opcache.revalidate_path => Off => Off
opcache.save_comments => 1 => 1
opcache.use_cwd => On => On
opcache.validate_timestamps => On => On
```

Any ideas?

**Comment by ovanschie** [comment]
Do you use config caching or routing caching? Also, can you try the update from yesterday (1.1) ?

**Comment by brentpep** [comment]
I'm using config caching and route caching, which I cleared as well. I also just tried v1.1 and still getting the same "connection refused" error.

Have you (or anyone) tested this inside of a docker container before and it work as expected? The weird part is it's not even working on Laravel Forge.

**Comment by ovanschie** [comment]
I have not tested it in Docker, only homestead and Forge without problems. So I can not say something about the connection issue with Docker. 

The 404 issue is probably one of the two problems; caching issue or wrong APP_URL. 
The command makes a request to <APP_URL>/opcache-api/<action> it registers the routes so they should be accessible.

**Comment by brentpep** [comment]
Thanks @ovanschie, I got it working in Forge!

**Comment by ovanschie** [comment]
What was the problem?

**Comment by brentpep** [comment]
I actually ended up having to restart the php-fpm service (which turns out clears opcache as well).

**Comment by ovanschie** [comment]
That is right, good to know it works on Forge now.

**Comment by summerblue** [comment]
In my case, first i clear the cache:

    php artisan api:cache

second:

    service php7.1-fpm restart

**Comment by pilishen** [comment]
BTW, when you set url in your env file, do not forget the `http://` or `https://` prefix

**Comment by denizaygun** [comment]
Not sure if this helps anyone but for me the issue was on our test server we had an extra forward-slash "/" at the end of the APP_URL 

So having `APP_URL=https://example.test/` breaks but without the last "/" it doesn't

**Comment by amir9480** [comment]
For anyone who uses Laradock for local development, I fix this problem by changing `/etc/hosts` of workspace container.

First, use `docker ps` and find Nginx container ID.
Then run `docker inspect NGINX_CONTAINER_ID` and find `"IPAddress"` in output.
```
 "Networks": {
  "laradock_backend": {
    ...
    "Gateway": "172.20.0.1",
    "IPAddress": "172.20.0.10", // THIS
    ...
  }
 }
```
Enter the workspace container.
```
docker exec -it WORKSPACE_CONTAINER_ID /bin/bash
```
Edit `/etc/hosts`:
`vi /etc/hosts`
and add your Nginx IP and your website virtual host like this:
```
x.x.x.x     virtualhost.local
```
Which in my case was:
```
172.20.0.10     site.local
```
