### ISSUE TITLE
Package not usable after a Load balancer and with more instances

### ISSUE THREAD

**Issue by glamorous** [appstract/laravel-opcache#28]
We wanted to use this package in our deploy scripts to flush the cache but because of the APP_URL usage in the code only one "random" instance will be selected and flushed if we set the APP_URL to something different then localhost (the default). Is it a possibility to use a different paramater or always use localhost (hardcoded) instead of using APP_URL. That way, a possible loadbalancer will never matter, but only the instance itself is available.

**Comment by ovanschie** [comment]
This is not possible at the moment. Your suggestion might not work when there are more sites installed on the same server, so maybe we have to find another way.

**Comment by glamorous** [comment]
Valid point, another way is to use a different environment variable (or the option to use another one) then APP_URL. We've now hacker it by overriding the variable at runtime in our Linux command so we don't neef to hack the package 😉 It's a dirty way to not change the code. We could possibly find another way but then we should make a PR and we didn't kwew if that is wanted 😁

**Comment by ovanschie** [comment]
I think having another config option would do no harm. Will have a look at it later 👍

**Comment by glamorous** [comment]
Another possible option is use also another server variable that is widely used with loadbalancers in the authentication-check: https://github.com/appstract/laravel-opcache/blob/master/src/Http/Middleware/Request.php#L26 => X_FORWARDED_FOR

**Comment by ovanschie** [comment]
I don't see how that is related

**Comment by glamorous** [comment]
There are 2 issues:
- The code throws authentication error when you're after a load balancer. I guess to current code works well after Cloudflare because off the check on `HTTP_CF_CONNECTING_IP`, other servervariables can be checked to, that are widely used by loadbalacers (that's why it is "related")
- The other issue is that calling a specific url only works if the website only lives on one app-server. To "cover" that localhost must be used, this can be done with another config URL or with another flag/option.

**Comment by ovanschie** [comment]
I added the config option and x-forwarded header. Can you give it a try (use dev-master as version in composer.json)?

You can set the url with the option OPCACHE_URL in .env

**Comment by glamorous** [comment]
We have tested it and the extra option OPCACHE_URL works great!

**Comment by ovanschie** [comment]
New release is tagged, so you can restore your composer.json if you want.

And don't forget to star :) ⭐️ ⭐️
