### ISSUE TITLE
[Feature-Request] Customize paths

### ISSUE THREAD

**Issue by ricardovf** [appstract/laravel-opcache#32]
Would be good to be able to add custom paths to the paths list on the optimize. I have other folders with code that do not live in /app. Why not optimize all files? Like all files in the vendor folder?

        // Get files in these paths
        $files = File::allFiles([
            base_path('app'),
            base_path('bootstrap'),
            base_path('storage/framework/views'),
            base_path('routes'),
            base_path('vendor/laravel/framework'),
        ]);

**Comment by ovanschie** [comment]
Optimizing all the files in vendor does not work and gives errors, that's why. If you want to make a pr so you can add custom paths, then that is welcome.
