### ISSUE TITLE
Purge behind htaccess

### ISSUE THREAD

**Issue by mtx-z** [appstract/laravel-opcache#34]
Hello ! Thanks a lot for this really great package. 
I have my dev server behind a htaccess, and so the purge is answered with a 401 code. Any way to add password to the request from config ? thanks.

**Comment by ovanschie** [comment]
I think this will work; put in your env:

OPCACHE_URL=http://username:password@appurl.com

**Comment by mtx-z** [comment]
Cool ! Fast reply thanks :) I'll test it soon ! Thanks.

**Comment by teuunn** [comment]
Good luck. Tested it and works fine for me. I'll close the issue. Please reopen if it didn't solve you problem.
