### ISSUE TITLE
The payload is invalid

### ISSUE THREAD

**Issue by xKairu** [appstract/laravel-opcache#39]
```
Appstract\LushHttp\Exception\LushRequestException The requested URL returned error: 500 Internal Server Error 
Illuminate\Contracts\Encryption\DecryptException The payload is invalid. 

Appstract\Opcache\Http\Middleware\Request::isAllowed line 40
```

Been fine on 1.1.x for a while now, until I updated to 1.2 today. I can only assume this is due to my instances being behind CloudFlare + AWS load balancer. I've tried reverting back to 1.1.6 with no success. Not sure why it's failing all of a sudden. Am I doing something wrong? All servers share the same environment, so the key is the same across all instances, and I have OPCACHE_URL set to localhost.

I can SSH into my instances (still 1.1.6 because I use Envoyer, so the 1.2 deploy fails), and it clears fine, so I have no idea why it would still fail when reverting to 1.1.6.

**Comment by ovanschie** [comment]
Can you try to restart your webserver? (nginx, apache, ..)

**Comment by xKairu** [comment]
Yup, I tried restarting PHP, nginx and the servers entirely and nothing changed.

**Comment by ovanschie** [comment]
Can you try the dev-master version? Included a catch for the exception, maybe it helps

**Comment by xKairu** [comment]
Seemed to pass successfully with "Opcode cache cleared" on each server, thanks.
