### ISSUE TITLE
Call to undefined function Appstract\Opcache\encrypt()

### ISSUE THREAD

**Issue by mtx-z** [appstract/laravel-opcache#42]
Hey there !

I'm having a issue after updating to ^1.2. I'm running Laravel 5.1, and all was ok.
I was previously on ^1.1, and it broke after a `composer update`. I tried to update to ^1.2 but still the same.

Any of the artisan command will throw `Call to undefined function Appstract\Opcache\encrypt()`.

`local.CRITICAL: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined function Appstract\Opcache\encrypt() in \vendor\appstract\laravel-opcache\src\CreatesRequest.php:16`

Thanks for your help !

EDIT: downgrading from 1.2.1 to 1.1.0 fixes the issue.
Seems related: #30

**Comment by ovanschie** [comment]
Should be fixed now when using Laravel 5.1

**Comment by mtx-z** [comment]
Will confirm when tested. Thanks for reactivity !
