### ISSUE TITLE
ErrorException: Undefined index: LOCAL_ADDR

### ISSUE THREAD

**Issue by jpuck** [appstract/laravel-opcache#43]
* Ubuntu Linux Server 16.04.2
* Apache/2.4.18
* PHP 7.0.18

I deployed an update to my server and when running:

    php artisan opcache:clear

I get an error:

>     ErrorException: Undefined index: LOCAL_ADDR in /.../vendor/appstract/laravel-opcache/src/Http/Middleware/Request.php:79
>     Stack trace:
>     #0 /.../vendor/appstract/laravel-opcache/src/Http/Middleware/Request.php(79): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '/var/www/overri...', 79, Array)
>     #1 /.../vendor/appstract/laravel-opcache/src/Http/Middleware/Request.php(47): Appstract\Opcache\Http\Middleware\Request->getServerIp()
>     #2 /.../vendor/appstract/laravel-opcache/src/Http/Middleware/Request.php(25): Appstract\Opcache\Http\Middleware\Request->isAllowed(Object(Illuminate\Http\Request))
>     #3 /.../vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Appstract\Opcache\Http\Middleware\Request->handle(Object(Illuminate\Http\Request), Object(Closure))
>     #4 /.../vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
>     #5 /.../vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
>     #6 /.../vendor/laravel/framework/src/Illuminate/Routing/Router.php(576): Illuminate\Pipeline\Pipeline->then(Object(Closure))
>     #7 /.../vendor/laravel/framework/src/Illuminate/Routing/Router.php(535): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
>     #8 /.../vendor/laravel/framework/src/Illuminate/Routing/Router.php(513): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
>     #9 /.../vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
>     #10 /.../vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
>     #11 /.../vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
>     #12 /.../vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
>     #13 /.../vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
>     #14 /.../vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
>     #15 /.../vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
>     #16 /.../vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
>     #17 /.../vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
>     #18 /.../vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
>     #19 /.../vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
>     #20 /.../vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
>     #21 /.../vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
>     #22 /.../vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
>     #23 /.../vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
>     #24 /.../vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
>     #25 /.../vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
>     #26 /.../public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
>     #27 {main}

This is quite bizarre because [the code on that line][1] clearly checks first with `isset` so I have no idea what's causing this.

However, the fix for me was to restart apache, and then `opcache:clear` worked fine.

[1]:https://github.com/appstract/laravel-opcache/blob/609dcdefeb78cdaaa70bbb047450a3f97682cc51/src/Http/Middleware/Request.php#L79

**Comment by ovanschie** [comment]
Thanks for the heads up, should be fixed now
