### ISSUE TITLE
Crypt not found

### ISSUE THREAD

**Issue by smecnarowski** [appstract/laravel-opcache#45]
For error class 'Crypt' not found please fix in Request.php middleware and in CreateRequest.php files: 
change `use Crypt;` to `use Illuminate\Support\Facades\Crypt;`

**Comment by teuunn** [comment]
Hi @smecnarowski,

Are you sure you have set the default aliases in config -> app.php?

`'Crypt' => \Illuminate\Support\Facades\Crypt::class,`

Crypt have been around at least since L5.1.

**Comment by smecnarowski** [comment]
Hi @teuunn 
I'm using Lumen 5.4.* there is no place for defining aliases by default

**Comment by teuunn** [comment]
@smecnarowski makes sense now! Released a new tag to fix it.

If you still have problems with this, feel free to reopen. And if you like the package, please consider to [star](https://github.com/appstract/laravel-opcache/stargazers).
