### ISSUE TITLE
laravel 5.4.25 配置好服务提供者未曾发现 opcache 的相关路由

### ISSUE THREAD

**Issue by mygrows** [appstract/laravel-opcache#47]
laravel 5.4.25，在 .evn 文件中定义了 OPCACHE_URL ,使用 php artisan route:list 没有发现有相关的 opcache  路由，在  phpstorm 的 Terminal 中 执行 php artisan list  也没有发现 opcache 相关的命令 如：php artisan opcache:clear ,望大神指点 :)

**Comment by ovanschie** [comment]
What is the problem?
