### ISSUE TITLE
run php artisan opcache:config and meet error

### ISSUE THREAD

**Issue by alexli0707** [appstract/laravel-opcache#50]
Thanks for sharing first,but when I require laravel-opache and run php artisan opcache:config and I got this error.Can you help me?Thanks
```
php artisan opcache:config
SSL: certificate subject name ‘*.newgame.com’ does not match target host name ‘localhost’
Url: http://localhost/opcache-api/config?key=eyJpdiI6InluYmZPb3pHU09od0FKc2s2Y1FoY1E9PSIsInZhbHVlIjoiTHRBdTVTUll4bUhyaTFEMjV4TUNUZz09IiwibWFjIjoiNmM0YTI3YzZjMDI3NjNkNDYyZDcxZDc3YTI2YTgwMGQ3NTExN2E0ODAwMTJkNDBkNDM0MWZkNTBiZmU3NTAzNCJ9

**Comment by ovanschie** [comment]
Make sure your APP_URL is set correctly in .env. If you want to set a different url to call the OPcache routes (for use with a load balancer for example), you can set OPCACHE_URL.

**Comment by ovanschie** [comment]
If you still have the issue, please reply. I will close it for now
