### ISSUE TITLE
403 Forbidden on every opcache command

### ISSUE THREAD

**Issue by Peeet93** [appstract/laravel-opcache#54]
I installed opcache via "composer require appstract/laravel-opcache" and set my APP_URL to "http://localhost:8000" and are running my app with "php artisan serve" i can access the requested url in the browser but not through the console. What did i do wrong?

**Comment by ovanschie** [comment]
Sorry, i don't have experience with artisan serve, maybe someone else could help. Did you have any luck deploying it to a server?

**Comment by teuunn** [comment]
Closed due to inactivity
