### ISSUE TITLE
Need ability to ignore SSL errors in artisan commands

### ISSUE THREAD

**Issue by maksimru** [appstract/laravel-opcache#55]
```bash
php artisan opcache:clear
Unable to communicate securely with peer: requested domain name does not match the server's certificate.
Url: https://localhost/opcache-api/clear?key=...

curl -v --insecure https://localhost/opcache-api/clear?key=...
{"result":true}
```

**Comment by maksimru** [comment]
seems related to #50 
localhost domain can't meet SSL requirements and i don't have 80 port on my webserver - only SSL

**Comment by ovanschie** [comment]
Will have a look at this. In the meantime, can't you use the full domain?

**Comment by maksimru** [comment]
I can't use full domain, because i have load balancer with multiple replications of the app, so call via domain will clean cache but on random instance instead of exact machine

**Comment by ovanschie** [comment]
I pushed a new option to the master branch. You can now set `'verify_ssl' => false,` in the config.

Can you try the dev-master version and see if this fixes it for you?

**Comment by maksimru** [comment]
Not clear how to use it right now since we are able to change only OPCACHE_URL via env var and we don't have config file published

**Comment by ovanschie** [comment]
you can publish it with 

php artisan vendor:publish --provider="Appstract\Opcache\OpcacheServiceProvider"

**Comment by ovanschie** [comment]
Any updates on this?

**Comment by maksimru** [comment]
It seems vendor publish command with OpcacheServiceProvider doesn't work on laravel 5.5

**Comment by rbruhn** [comment]
Confirming verify_ssl => false works
As @maksimru states, publish command not working in L5.5

**Comment by jamesmills** [comment]
> I can't use full domain, because i have load balancer with multiple replications of the app, so call via domain will clean cache but on random instance instead of exact machine

Did you figure out a way to run this on all servers behind LB?
