### ISSUE TITLE
SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by jaketoolson** [appstract/laravel-opcache#58]
`php artisan opcache:optimize`

Optimize started, this can take a while...
SSL certificate problem: unable to get local issuer certificate
Url: http://localhost.com/opcache-api/optimize?key=eyJpdiI6IlZWcXRYVG5lTFFcL2dDT3huREJYbVZRPT0iLCJ2YWx1ZSI6ImNFTHZjTDZQRXZkTTFQU3BsQ2FRZXc9PSIsIm1hYyI6IjhkZWM0OGRmYmE0MmUxYWFlYjAxMjVmNTc4YjE0MDlhMDAzMzI5YTIwMjk3MmE0MDMyNjEwZDhkODZjM2U1OTIifQ%3D%3D

Using Laravel 5.4, PHP 7.1

**Comment by ovanschie** [comment]
see #55

**Comment by rbruhn** [comment]
I'm having this same issue but I do have a URL

SSL certificate problem: unable to get local issuer certificate
Url: https://biospex2.loc/opcache-api/clear?key=eyJpdiI6IlhtYVF6aDdnVHM4XC9iNVFHYXY2dmdBPT0iLCJ2YWx1ZSI6Im85OGlwS1kwa3hBNFY1MlwvZW1Da3B3PT0iLCJtYWMiOiI5ZTc0YTA5NTE1ZTNiZDViNGRlNGVmMjg2YjMxODc4ZmRiYWRhNzNhNDZmOGRmNTUwZGZiYWRmMTdkMzgwOTJhIn0%3D

**Comment by ovanschie** [comment]
Should be fixed see #55
