### ISSUE TITLE
Cannot declare class Illuminate\Session\SessionManager

### ISSUE THREAD

**Issue by fridzema** [appstract/laravel-opcache#59]
Hello, 

When i execute php artisan `opcache:optimize` in the terminal i get normal output: `892 of 1055 files optimized`
But every time i do this, there is a log written with:
Cannot declare class Illuminate\Session\SessionManager, because the name is already in use

Any idea whats causing this?

**Comment by chrisLeeTW** [comment]
Hi, I have also the same problem, but with different class.

```Cannot declare class Illuminate\Support\ServiceProvider, because the name is already in use```
