### ISSUE TITLE
fix for Issue #55 broken usage for lumen.

### ISSUE THREAD

**Issue by chrisLeeTW** [appstract/laravel-opcache#61]
@ovanschie Hi,

I found out that this commit f70f79b8b994ac93bddeb9b17dd16d9da85f8e87 broken the usage for lumen. It will throw this exception when bootstrapping 
```
[Symfony\Component\Debug\Exception\FatalThrowableError]
Call to undefined function Appstract\Opcache\config_path()
```
due to lack of config_path help functions for lumen.

**Comment by ovanschie** [comment]
Thanks for noticing and the PR!
