### ISSUE TITLE
Error on running php artisan opcache:optimize

### ISSUE THREAD

**Issue by dazzcreations** [appstract/laravel-opcache#64]
Hello, I have recently included appstract/laravel-opcache in my laravel 5.4.36 project. When i am running  `php artisan opcache:optimize` command i am getting the following error 

Symfony\Component\Debug\Exception\FatalErrorExceptionGET /opcache-api/optimize
Cannot declare trait Illuminate\Auth\Access\HandlesAuthorization, because the name is already in use

I have checked the source of my application and it doesn't use it anywhere.

Can you help me with this issue?

**Comment by dazzcreations** [comment]
Anyone?

**Comment by xakzona** [comment]
composer dumpautoload
