### ISSUE TITLE
cmnds error

### ISSUE THREAD

**Issue by ctf0** [appstract/laravel-opcache#7]
first many thanx for this package & for the article as well.

atm am getting error on each run of `opcache:config`, sometimes it could be
```bash
 [ErrorException]
  Trying to get property of non-object
```

or
```bash
 [GuzzleHttp\Exception\RequestException]
  cURL error 56: Recv failure: Connection reset by peer (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
```

**Comment by ovanschie** [comment]
Only get this with the config command? Where are you running the command (inside vm, inside os terminal, on your server)?

**Comment by ctf0** [comment]
OSX 10.11.6
PHP 7.0.15 (cli)
Laravel 5.3.30

if u need more info just tell me 👍

**Comment by ovanschie** [comment]
Yes, I tried with the newest guzzle version an ran the tests. 

Can you answer my second question please?:
Where are you running the command (inside vm, inside os terminal, on your server)?

**Comment by ctf0** [comment]
> OSX 10.11.6

inside os terminal :white_check_mark:

**Comment by ovanschie** [comment]
Where is your server running, inside VM (homestead) or do you use something else?

Also, have you set the correct APP_URL in .ENV to correspond with your application URL?

**Comment by ctf0** [comment]
no, on mac itself using php installed with brew
for the url , i tried with both `valet` & `php artisan` which is `http://localhost`

**Comment by ctf0** [comment]
**update**

the error is no longer showing up, i update lara to `v5.4` and guzzle is already pre-installed to `6.2.2 `
however one thing to note, using `APP_URL=http://localhost` will give error, instead of `php artisan` use `valet` and change `app_url` to `APP_URL=http://your-site.dev`
