### ISSUE TITLE
opcache bug

### ISSUE THREAD

**Issue by Leslie1sMe** [appstract/laravel-opcache#78]
At first i wanna say the opcache really accecreate my application, however,thing dont always go well, when i use php artisan opcache:optimize ,the PHP will throw a fatal exception like "Cannot declare class Illuminate\Routing\Redirector, because the name is already in use" it really confused me ,help me !

**Comment by ovanschie** [comment]
Try the new version

**Comment by Leslie1sMe** [comment]
well ..but brother it has been a long time till i gave the issue .. i never use laravel or php right now, what a pity
