### ISSUE TITLE
Middleware 'bindings'

### ISSUE THREAD

**Issue by koss-shtukert** [appstract/laravel-opcache#8]
Hi there!
I have some error after install laravel-opcache

> ReflectionException: Class bindings does not exist

As i see you add middleware 'bindings'  and \Appstract\Opcache\Http\Middleware\Request in your route group...

`'middleware'    => ['bindings', \Appstract\Opcache\Http\Middleware\Request::class],`

How to fix it?

**Comment by koss-shtukert** [comment]
Solve this problem, 
`'bindings' => \Illuminate\Routing\Middleware\SubstituteBindings::class,`
Added in Laravel 5.3

**Comment by ovanschie** [comment]
I removed the bindings middleware in the new release, can you give it a try?
