### ISSUE TITLE
Cannot use Riak\Object as Object because 'Object' is a special class name

### ISSUE THREAD

**Issue by rariteth** [appstract/laravel-opcache#92]
when i run artisan opcache:compile I get that error:

<img width="702" alt="image" src="https://user-images.githubusercontent.com/204567/66486406-3625c000-eab3-11e9-9f7a-4f6afeeeb24a.png">

**Comment by ovanschie** [comment]
https://stackoverflow.com/questions/55401033/error-riak-object-dont-want-update-column-of-table
