### ISSUE TITLE
 URL is invalid?

### ISSUE THREAD

**Issue by zhsk** [appstract/laravel-opcache#93]
Administrator@HL-20190403GOTW MINGW64 /e/www/tiku_server/tiku_admin (master)
$ php artisan opcache:clear

In LushRequest.php line 69:

  URL is invalid

**Comment by ovanschie** [comment]
Did you set the correct APP_URL?

**Comment by WadhahEssam** [comment]
I set it up and still have this problem, is there any solution to it
