### ISSUE TITLE
PHP 7.4 Preload Support

### ISSUE THREAD

**Issue by mpyw** [appstract/laravel-opcache#96]
- [PHP：rfc：preload](https://wiki.php.net/rfc/preload)

> `opcache_reset()` is not going to reload preloaded files. It's just not possible using current opcache design, because during restart, they may be used by some process, and any modifications may lead to crash.

Still we can provide `opcache:compile` as an entrypoint for `opcache.preload`.

**Comment by ovanschie** [comment]
Should work if you put this code in a php script in your Laravel project, and point to the file.

```php
<?php

echo shell_exec("php artisan opcache:compile --force");


```
